### ISSUE TITLE
Get-GuestConfigurationPackageComplianceStatus nxFile fails

### ISSUE THREAD

**Issue by MattGarnerAWR** [SynEdgy/nxtools#19]
I have built a simple nxFile configuration:

Configuration myDscExample {
    Import-DSCResource -Module PSDesiredStateConfiguration, nxtools
    node localhost {
        nxFile "myTestFile" {
            Ensure          = "Present"
            Type            = "File"
            DestinationPath = "/tmp/helloFromDsc"
            Contents        = "Hello DSC for Linux!"
        }
    }
}

When trying to test this using GuestConfiguration it fails: 

Get-GuestConfigurationPackageComplianceStatus -path ./test2.zip
Error: Failed to Run Consistency for 'test2' Error : Exception calling "Invoke" with "0" argument(s): "Exception calling ".ctor" with "1" argument(s): "Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en-US is an invalid culture identifier.""
The property 'Type' cannot be found on this object. Verify that the property exists and can be set.
The property 'Contents' cannot be found on this object. Verify that the property exists and can be set.
The property 'DestinationPath' cannot be found on this object. Verify that the property exists and can be set.
The property 'Ensure' cannot be found on this object. Verify that the property exists and can be set.
You cannot call a method on a null-valued expression.
InvokeDscResource() failed. errorMessage:The PowerShell DSC resource with className:nxFile moduleName:nxtools moduleVersion:0.2.0 threw one or more non-terminating errors, while running the Get-DscResource functionality
The PowerShell DSC resource with className:nxFile moduleName:nxtools moduleVersion:0.2.0 threw one or more non-terminating errors, while running the Get-DscResource functionality

**Comment by MattGarnerAWR** [comment]
@gaelcolas  FYI

**Comment by gaelcolas** [comment]
Yep, I'm afraid this repo is not the official repo...
The official repo is at Azure/nxtools, but it is not Open Sourced yet (still private) and hasn't been released in a while (waiting on Microsoft but the fix is merged on `main`).
I think we're only waiting for @jaykul to publish https://github.com/PoshCode/ModuleBuilder/pull/120 and then @juliamwang6 can release and publish nxtools...
